[[ranks]]
  tier = 0
  numAffixes = 0
  defaultColor = 0xffffff
  chance = 1.0
  growthFactor = 0
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 1
  numAffixes = 1
  defaultColor = 0xffff00
  chance = 0.05
  growthFactor = 1
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 2
  numAffixes = 2
  defaultColor = 0xff9900
  chance = 0.15
  growthFactor = 4
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 3
  numAffixes = 3
  defaultColor = 0x66ffff
  chance = 0.3
  growthFactor = 9
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 4
  numAffixes = 4
  defaultColor = 0xcc33ff
  chance = 0.4
  growthFactor = 16
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 5
  numAffixes = 5
  defaultColor = 0x55ff55
  chance = 0.5
  growthFactor = 25
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 6
  numAffixes = 6
  defaultColor = 0x55ffff
  chance = 0.5
  growthFactor = 36
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 7
  numAffixes = 7
  defaultColor = 0xff5555
  chance = 0.5
  growthFactor = 49
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 8
  numAffixes = 8
  defaultColor = 0xff55ff
  chance = 0.5
  growthFactor = 81
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 9
  numAffixes = 9
  defaultColor = 0xffff55
  chance = 0.5
  growthFactor = 1000
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 10
  numAffixes = 10
  defaultColor = 0xddd605
  chance = 0.3
  growthFactor = 3072
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 11
  numAffixes = 11
  defaultColor = 0x000000
  chance = 0.05
  growthFactor = 8000
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 12
  numAffixes = 12
  defaultColor = 0xffffff
  chance = 0.05
  growthFactor = 10240
  effects = []
  presetAffixes = []
