
#Titanium Ore Worldgen
[titanium_ore]
	#Enable/Disable Titanium ore
	titaniumOreEnabled = true
	#Min Y level
	#Range: -60 ~ 0
	minY = -20
	#Max Y Level
	#Range: -60 ~ 20
	maxY = -10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Altairium Ore Worldgen
[altairium_ore]
	#Enable/Disable Altairium ore
	altairiumOreEnabled = true
	#Min Y level
	#Range: -10 ~ 50
	minY = 10
	#Max Y Level
	#Range: 20 ~ 60
	maxY = 30
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Halleium Ore Worldgen
[halleium_ore]
	#Enable/Disable Halleium ore
	halleiumOreEnabled = true
	#Min Y level
	#Range: -60 ~ 0
	minY = -20
	#Max Y Level
	#Range: -60 ~ 20
	maxY = -10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Hothium Ore Worldgen
[hothium_ore]
	#Enable/Disable Hothium ore
	hothiumOreEnabled = true
	#Min Y level
	#Range: -10 ~ 50
	minY = 10
	#Max Y Level
	#Range: 20 ~ 60
	maxY = 30
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Immersed Silver Ore Worldgen
[immersedsilver_ore]
	#Enable/Disable ImmersedSilver ore
	immersedSilverOreEnabled = true
	#Min Y level
	#Range: 10 ~ 50
	minY = 30
	#Max Y Level
	#Range: 20 ~ 70
	maxY = 40
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Inert Witherium Ore Worldgen
[inertwitherium_ore]
	#Enable/Disable Inertwitherium ore
	inertwitheriumOreEnabled = true
	#Min Y level
	#Range: 0 ~ 60
	minY = 5
	#Max Y Level
	#Range: 2 ~ 85
	maxY = 10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 8
	#Ore vein size
	#Range: 1 ~ 7
	veinSize = 3

#Steamium Ore Worldgen
[steamium_ore]
	#Enable/Disable Steamium ore
	steamiumOreEnabled = true
	#Min Y level
	#Range: -60 ~ 0
	minY = -20
	#Max Y Level
	#Range: -60 ~ 20
	maxY = -10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Stellarium Ore Worldgen
[stellarium_ore]
	#Enable/Disable Stellarium ore
	stellariumOreEnabled = true
	#Min Y level
	#Range: -60 ~ 0
	minY = -20
	#Max Y Level
	#Range: -60 ~ 20
	maxY = -10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Magiga Ore Worldgen
[magiga_ore]
	#Enable/Disable Magiga ore
	magigaOreEnabled = true
	#Min Y level
	#Range: -60 ~ 0
	minY = -20
	#Max Y Level
	#Range: -60 ~ 20
	maxY = -10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Tonium Ore Worldgen
[tonium_ore]
	#Enable/Disable Tonium ore
	toniumOreEnabled = true
	#Min Y level
	#Range: -60 ~ 0
	minY = -20
	#Max Y Level
	#Range: -60 ~ 20
	maxY = -10
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

